import * as monaco from 'monaco-editor';
import * as _ from 'lodash';

export const MonacoMap = {
  Backspace: monaco.KeyCode.Backspace,
  Tab: monaco.KeyCode.Tab,
  Enter: monaco.KeyCode.Enter,
  Shift: monaco.KeyCode.Shift,
  ' ': monaco.KeyCode.Space,
  ArrowUp: monaco.KeyCode.UpArrow,
  ArrowLeft: monaco.KeyCode.LeftArrow,
  ArrowRight: monaco.KeyCode.RightArrow,
  ArrowDown: monaco.KeyCode.DownArrow,
  Delete: monaco.KeyCode.Delete,
  Escape: monaco.KeyCode.Escape,
  '[': monaco.KeyCode.BracketLeft,
  ']': monaco.KeyCode.BracketRight,
  '0': monaco.KeyCode.Digit0,
  '1': monaco.KeyCode.Digit1,
  '2': monaco.KeyCode.Digit2,
  '3': monaco.KeyCode.Digit3,
  '4': monaco.KeyCode.Digit4,
  '5': monaco.KeyCode.Digit5,
  '6': monaco.KeyCode.Digit6,
  '7': monaco.KeyCode.Digit7,
  '8': monaco.KeyCode.Digit8,
  '9': monaco.KeyCode.Digit9,
  a: monaco.KeyCode.KeyA,
  b: monaco.KeyCode.KeyB,
  c: monaco.KeyCode.KeyC,
  d: monaco.KeyCode.KeyD,
  e: monaco.KeyCode.KeyE,
  f: monaco.KeyCode.KeyF,
  g: monaco.KeyCode.KeyG,
  h: monaco.KeyCode.KeyH,
  i: monaco.KeyCode.KeyI,
  j: monaco.KeyCode.KeyJ,
  k: monaco.KeyCode.KeyK,
  l: monaco.KeyCode.KeyL,
  m: monaco.KeyCode.KeyM,
  n: monaco.KeyCode.KeyN,
  o: monaco.KeyCode.KeyO,
  p: monaco.KeyCode.KeyP,
  q: monaco.KeyCode.KeyQ,
  r: monaco.KeyCode.KeyR,
  s: monaco.KeyCode.KeyS,
  t: monaco.KeyCode.KeyT,
  u: monaco.KeyCode.KeyU,
  v: monaco.KeyCode.KeyV,
  w: monaco.KeyCode.KeyW,
  x: monaco.KeyCode.KeyX,
  y: monaco.KeyCode.KeyY,
  z: monaco.KeyCode.KeyZ,
  F1: monaco.KeyCode.F1,
  F2: monaco.KeyCode.F2,
  F3: monaco.KeyCode.F3,
  F4: monaco.KeyCode.F4,
  F5: monaco.KeyCode.F5,
  F6: monaco.KeyCode.F6,
  F7: monaco.KeyCode.F7,
  F8: monaco.KeyCode.F8,
  F9: monaco.KeyCode.F9,
  F10: monaco.KeyCode.F10,
  F11: monaco.KeyCode.F11,
  F12: monaco.KeyCode.F12,
  F13: monaco.KeyCode.F13,
  F14: monaco.KeyCode.F14,
  F15: monaco.KeyCode.F15,
  F16: monaco.KeyCode.F16,
  F17: monaco.KeyCode.F17,
  F18: monaco.KeyCode.F18,
  F19: monaco.KeyCode.F19,
  '.': monaco.KeyCode.Period,
  ',': monaco.KeyCode.Comma,
  '\\': monaco.KeyCode.Backslash,
  '/': monaco.KeyCode.Slash,
  PageUp: monaco.KeyCode.PageUp,
  PageDown: monaco.KeyCode.PageDown,
  Home: monaco.KeyCode.Home,
  End: monaco.KeyCode.End,
  '-': monaco.KeyCode.Minus,
  '=': monaco.KeyCode.Equal
};

export const MonacoMapInverted = _.invert(MonacoMap);
